pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                dir('producer-pipeline'){
                    echo 'Cleaning...'
                    sh 'ls'
                    sh 'mvn clean'
                }

            }
        }
        stage('Test') {
            steps {
                dir('producer-pipeline'){
                    echo 'Testing...'
                    sh 'mvn test'
                }
            }
        }
        stage('Compile') {
            steps {
                dir('producer-pipeline'){
                    echo 'Compiling...'
                    sh 'mvn compile'
                }
            }
        }
        stage('Final Clean') {
            steps {
                dir('producer-pipeline'){
                    echo 'Cleaning...'
                    sh 'mvn clean'
                    sh 'ls'
                }
            }
        }
    }
}