pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                dir('streams-pipeline'){
                    echo 'Cleaning...'
                    sh 'ls'
                    sh 'mvn clean'
                }

            }
        }
        stage('Test') {
            steps {
                dir('streams-pipeline'){
                    echo 'Testing...'
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir('streams-pipeline'){
                    echo 'Compiling...'
                    sh 'mvn package'
                }
            }
        }
        stage('Build') {
            steps {
                dir('streams-pipeline'){
                    echo 'Building Docker Image...'
                    sh 'docker build -t streams-app:v1 .'
                }
            }
        }
        stage('Register') {
            steps {
                dir('streams-pipeline'){
                    echo 'Registering with Azure Container Registry...'
                    sh 'docker tag streams-app:v1 abeReg.azurecr.io/streams/streams-app'
                    sh 'docker push abeReg.azurecr.io/streams/streams-app'
                }
            }
        }
        stage('Final Clean') {
            steps {
                dir('streams-pipeline'){
                    echo 'Cleaning...'
                    sh 'mvn clean'
                    sh 'ls'
                }
            }
        }
    }
}